spring.data.mongodb.uri=mongodb+srv://ishachaudhari98_db_user:B8EUPwBZr72wSpTC@cluster0.hqtykfd.mongodb.net/test
spring.data.mongodb.database=test

splitwise.app.jwtSecret=splitwisePlusSuperSecretKeyThatIsAtLeast64CharactersLong1234567890abcdef
splitwise.app.jwtExpirationMs=604800000

server.port=8080