spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://ishachaudhari98_db_user:B8EUPwBZr72wSpTC@cluster0.hqtykfd.mongodb.net/test}
spring.data.mongodb.database=${MONGO_DB:test}

splitwise.app.jwtSecret=${JWT_SECRET:splitwisePlusSuperSecretKeyThatIsAtLeast64CharactersLong1234567890abcdef}
splitwise.app.jwtExpirationMs=604800000

server.port=${PORT:8080}